import type { CandidateProfile } from "@/types/candidate";

export const ericGrunblattProfile: CandidateProfile = {
  id: "candidate-eric-grunblatt",
  firstName: "Eric",
  lastName: "Grunblatt",
  email: "ericgrunblatt@gmail.com",
  phone: "(201) 669-2041",
  city: "Mahwah",
  state: "NJ",
  country: "USA",
  linkedInUrl: "https://www.linkedin.com/in/eric-grunblatt/",
  githubUrl: "https://github.com/EricGrunblatt",
  summary:
    "Senior software engineer focused on platform engineering, CI/CD, release governance, and observability with experience building enterprise developer tooling and large-scale migration programs.",
  remotePreference: "open",
  willingnessToRelocate: false,
  minimumSalary: 180000,
  preferredSalary: 220000,
  targetRoles: [
    "Senior Software Engineer",
    "Platform Engineer",
    "Senior DevOps Engineer",
    "Software Engineer",
    "Full Stack Engineer",
  ],
  preferredLocations: ["Remote - United States", "New York", "New Jersey"],
  skills: [
    { name: "Java", category: "Languages" },
    { name: "Python", category: "Languages" },
    { name: "JavaScript", category: "Languages" },
    { name: "TypeScript", category: "Languages" },
    { name: "SQL", category: "Languages" },
    { name: "HTML/CSS", category: "Languages" },
    { name: "Azure DevOps", category: "Platforms & DevOps" },
    { name: "GitHub Actions", category: "Platforms & DevOps" },
    { name: "Git", category: "Platforms & DevOps" },
    { name: "CI/CD", category: "Platforms & DevOps" },
    { name: "Grafana", category: "Observability & Monitoring" },
    { name: "Prometheus", category: "Observability & Monitoring" },
    { name: "Grafana Loki", category: "Observability & Monitoring" },
    { name: "PromQL", category: "Observability & Monitoring" },
    { name: "LogQL", category: "Observability & Monitoring" },
    { name: "Splunk", category: "Observability & Monitoring" },
    { name: "Node.js", category: "Frameworks & Databases" },
    { name: "Express.js", category: "Frameworks & Databases" },
    { name: "React.js", category: "Frameworks & Databases" },
    { name: "Vue.js", category: "Frameworks & Databases" },
    { name: "MySQL", category: "Frameworks & Databases" },
    { name: "MongoDB", category: "Frameworks & Databases" },
    { name: "Google Cloud Platform", category: "Cloud & Tools" },
    { name: "REST APIs", category: "Cloud & Tools" },
    { name: "Linux/Unix", category: "Cloud & Tools" },
  ],
  workExperiences: [
    {
      company: "GEICO Tech",
      title: "Senior Software Engineer",
      startDate: "2026-07-01",
      endDate: undefined,
      location: "United States",
      description: "Release Platform Team",
      current: true,
    },
    {
      company: "GEICO Tech",
      title: "Software Engineer II",
      startDate: "2025-07-01",
      endDate: "2026-06-30",
      location: "United States",
      description: "Release Platform Team",
      current: false,
    },
    {
      company: "GEICO Tech",
      title: "Software Engineer I",
      startDate: "2024-03-01",
      endDate: "2025-06-30",
      location: "United States",
      description: "Observability Team",
      current: false,
    },
    {
      company: "Revelwood Solutions",
      title: "Full Stack JavaScript Intern",
      startDate: "2022-06-01",
      endDate: "2022-08-31",
      location: "United States",
      description: "Built internal tools and maintained production web applications.",
      current: false,
    },
  ],
  education: [
    {
      school: "Stony Brook University",
      degree: "Bachelor of Science",
      major: "Computer Science",
      graduationDate: "2023-05-01",
      gpa: 3.58,
      location: "Stony Brook, NY",
    },
  ],
  projects: [],
  certifications: [],
  candidateFacts: [
    {
      id: "geico-release-platform-001",
      company: "GEICO Tech",
      role: "Senior Software Engineer",
      text: "Architected a standardized CI/CD pipeline framework in partnership with the Paved Road team, establishing consistent, reusable GitHub-based workflows for thousands of engineers and applications across the organization.",
      metrics: [],
      skills: ["CI/CD", "GitHub", "Platform Engineering", "Automation"],
      verified: true,
    },
    {
      id: "geico-release-platform-002",
      company: "GEICO Tech",
      role: "Senior Software Engineer",
      text: "Developed a standardized CD architecture supporting deployments across up to four environments with policy validation, artifact deployment, post-deployment testing, release creation, and change request procedures.",
      metrics: ["4 environments"],
      skills: ["Continuous Delivery", "Deployment Automation", "Release Engineering"],
      verified: true,
    },
    {
      id: "geico-release-platform-003",
      company: "GEICO Tech",
      role: "Software Engineer II",
      text: "Developed a release governance platform enforcing internal deployment policies across Azure DevOps and GitHub, validating over 15,000 deployment pipelines through Azure DevOps Pipeline Decorators and GitHub Deployment Protection Rules.",
      metrics: ["15,000 deployment pipelines"],
      skills: ["Azure DevOps", "GitHub", "Deployment Policy", "Platform Engineering"],
      verified: true,
    },
    {
      id: "geico-release-platform-004",
      company: "GEICO Tech",
      role: "Software Engineer II",
      text: "Automated onboarding and validation workflows, eliminating manual platform reviews and configuration, reducing onboarding effort from 30 minutes to 0 and increasing adoption from 10% to 100% of eligible pipelines.",
      metrics: ["30 minutes to 0", "10% to 100% adoption"],
      skills: ["Automation", "Developer Experience", "Workflow Design"],
      verified: true,
    },
    {
      id: "geico-observability-001",
      company: "GEICO Tech",
      role: "Software Engineer I",
      text: "Developed and supported GEICO's enterprise observability platform leveraging Grafana Loki and Prometheus, enabling organization-wide migration from Splunk across thousands of engineers.",
      metrics: ["thousands of engineers"],
      skills: ["Grafana Loki", "Prometheus", "Observability", "Splunk Migration"],
      verified: true,
    },
    {
      id: "geico-observability-002",
      company: "GEICO Tech",
      role: "Software Engineer I",
      text: "Partnered with engineering teams to migrate over 2,000 Splunk queries, 300 dashboards, and 500 alerts using LogQL and PromQL while improving query performance and observability efficiency.",
      metrics: ["2,000 Splunk queries", "300 dashboards", "500 alerts"],
      skills: ["LogQL", "PromQL", "Migration", "Observability"],
      verified: true,
    },
    {
      id: "revelwood-intern-001",
      company: "Revelwood Solutions",
      role: "Full Stack JavaScript Intern",
      text: "Developed internal web applications using JavaScript, TypeScript, and jQuery, including a Google Sheets extension for automated email workflows.",
      metrics: [],
      skills: ["JavaScript", "TypeScript", "jQuery", "Google Sheets", "Automation"],
      verified: true,
    },
    {
      id: "revelwood-intern-002",
      company: "Revelwood Solutions",
      role: "Full Stack JavaScript Intern",
      text: "Maintained and enhanced production applications built with Vue.js, Express.js, and MySQL supporting thousands of users.",
      metrics: ["thousands of users"],
      skills: ["Vue.js", "Express.js", "MySQL", "Production Support"],
      verified: true,
    },
  ],
  preferences: {
    employmentTypes: ["full_time"],
    industriesToPrefer: ["Fintech", "Insurance", "Technology", "Platform Engineering"],
    industriesToExclude: [],
    seniorityPreferences: ["senior", "staff"],
    desiredTechnologies: [
      "CI/CD",
      "Java",
      "AWS",
      "Kubernetes",
      "Observability",
      "Developer Platforms",
      "GitHub",
      "Terraform",
    ],
    locations: ["Remote - United States", "New York", "New Jersey"],
    preferredRemotePolicy: "remote",
    maxCommuteMiles: 50,
    notes: "Open to remote and hybrid roles with a strong preference for platform, devops, or software engineering work.",
  },
};
